apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: gatekeeper-validating-webhook-configuration
  annotations:
    # Placeholder, patch with the gatekeeper namespace value
    certmanager.k8s.io/inject-ca-from: example-namespace/gatekeeper-serving-cert
webhooks:
  - name: validation.gatekeeper.sh
    clientConfig:
      service:
        # Placeholder, patch with the gatekeeper namespace value
        namespace: example-namespace
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - "namespaces"
          - "ingresses"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gatekeeper-serving-cert
spec:
  # Placeholder, patch with the gatekeeper namespace value
  commonName: gatekeeper-webhook-service.example-namespace.svc
  dnsNames:
    # Placeholder, patch with the gatekeeper namespace value
    - gatekeeper-webhook-service.example-namespace.svc.cluster.local
