# sync namespaces and ingresses to gatekeeper
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
spec:
  sync:
    syncOnly:
      - version: "v1"
        kind: "Namespace"
      - version: "v1beta1"
        kind: "Ingress"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: gatekeeper-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gatekeeper-serving-cert
spec:
  # Placeholder, patch with the gatekeeper namespace value
  commonName: gatekeeper-webhook-service.example-namespace.svc
  dnsNames:
    # Placeholder, patch with the gatekeeper namespace value
    - gatekeeper-webhook-service.example-namespace.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: gatekeeper-selfsigned-issuer
  secretName: gatekeeper-webhook-server-cert
