# sync namespaces and ingresses to gatekeeper
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
spec:
  sync:
    syncOnly:
      - version: "v1"
        kind: "Namespace"
      - version: "v1beta1"
        kind: "Ingress"
