apiVersion: v1
kind: Secret
metadata:
  name: gatekeeper-webhook-server-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: gatekeeper-controller-manager-service
spec:
  ports:
    - port: 443
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: gatekeeper-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: gatekeeper-controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
        - args:
            - --auditInterval=30
          command:
            - /root/manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SECRET_NAME
              value: gatekeeper-webhook-server-secret
          image: quay.io/open-policy-agent/gatekeeper:v3.0.4-beta.1
          imagePullPolicy: Always
          name: manager
          ports:
            - containerPort: 443
              name: webhook-server
              protocol: TCP
          resources:
            limits:
              # increased from the relatively low defaults provided by the upstream manifest; 100m cpu caused very slow request
              # latencies to the api server
              cpu: 7000m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /certs
              name: cert
              readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: gatekeeper-webhook-server-secret
