version: 2.0
jobs:
  rego:
    machine: true
    steps:
      - checkout
      - run: docker build --target rego .
  kustomize:
    machine: true
    steps:
      - checkout
      - run: docker build --target kustomize .
workflows:
  version: 2
  test:
    jobs:
      - rego
      - kustomize
