apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: gatekeeper-validating-webhook-configuration
webhooks:
  - name: validation.gatekeeper.sh
    clientConfig:
      service:
        name: gatekeeper-webhook-service
        path: /v1/admit
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
    sideEffects: None
    timeoutSeconds: 5
