apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-audit
spec:
  template:
    spec:
      containers:
        - name: auditcontainer
          resources:
            limits:
              cpu: 7000m
              memory: 4000Mi
            requests:
              cpu: 200m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - --port=8443
            - --logtostderr
            - --emit-admission-events=false
            - --log-level=INFO
            - --exempt-namespace=$(POD_NAMESPACE)
            - --operation=webhook
            - --disable-cert-rotation
          resources:
            limits:
              cpu: 7000m
              memory: 4000Mi
            requests:
              cpu: 200m
